### ISSUE TITLE
Jelly mapping is failing

### ISSUE THREAD

**Issue by pgdurand** [pgdurand/pbsuite-docker#1]
After building the image, I did this :

    docker run -it --rm pbsuite-15.8.24
    cd /tmp
    Jelly setup protocol.xml
    Jelly mapping protocol.xml

The setup step seems to be ok (i.e. no error messages in log file).
However, the "mapping" step failed with this error message :

```
root@488897ddf544:/tmp# cat mapping/filtered_subreads.fastq.err 
2017-10-12 13:59:19,852 [INFO] Running /usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py /tmp/mapping/filtered_subreads.fastq.m4 /usr/share/doc/pbjelly/examples/data/reads/filtered_subreads.fastq /usr/share/doc/pbjelly/examples/data/reference/lambda.fasta --nproc 4 -i
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py", line 209, in <module>
    run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py", line 171, in run
    aligns = M4File(args.m4)
  File "/usr/lib/python2.7/dist-packages/pbsuite/utils/FileHandlers.py", line 484, in __init__
    file = open(file,'r')
IOError: [Errno 2] No such file or directory: '/tmp/mapping/filtered_subreads.fastq.m4'

```
After some investigation, it appears that "blastr" won't run as expected. 

I did this :

    blasr /usr/share/doc/pbjelly/examples/data/reads/filtered_subreads.fastq /usr/share/doc/pbjelly/examples/data/reference/lambda.fasta --minMatch 8 --minPctIdentity 70 --bestn 1 --nCandidates 20 --maxScore -500 --nproc 4 --noSplitSubreads > /tmp/mapping/filtered_subreads.fastq.m4

I started Jelly again :

    Jelly mapping protocol.xml

It failed with this error :

```
root@488897ddf544:/tmp# cat mapping/filtered_subreads.fastq.err 2017-10-12 14:03:43,371 [INFO] Running /usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py /tmp/mapping/filtered_subreads.fastq.m4 /usr/share/doc/pbjelly/examples/data/reads/filtered_subreads.fastq /usr/share/doc/pbjelly/examples/data/reference/lambda.fasta --nproc 4 -i
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py", line 209, in <module>
    run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pbsuite/jelly/m4pie.py", line 171, in run
    aligns = M4File(args.m4)
  File "/usr/lib/python2.7/dist-packages/pbsuite/utils/FileHandlers.py", line 486, in __init__
    self.__parse()
  File "/usr/lib/python2.7/dist-packages/pbsuite/utils/FileHandlers.py", line 492, in __parse
    self.append(M4Line(line.strip()))
  File "/usr/lib/python2.7/dist-packages/pbsuite/utils/FileHandlers.py", line 508, in __init__
    self.qstart         = int(data[5])
ValueError: invalid literal for int() with base 10: '87.197'
```

**Comment by oswinHu** [comment]
hello pgdurand!
I had the same problem with mapping .
Did you solve it ? could you share your solution?

**Comment by JJZhao123** [comment]
I had the same problem before, I solved with downgrading the blasr version to  1.3.1
https://github.com/BioInf-Wuerzburg/proovread/blob/master/util/blasr-1.3.1/blasr

**Comment by StephanHolgerD** [comment]
just in case anybody is still interested in a working dockerfile for pbsuite, i but one up 

https://github.com/StephanHolgerD/PBsuite-Dockerfile

**Comment by wuxiaopei0509** [comment]
I downgrade the blasr version to 1.3.1，but the the mapping stage still doesn't work .could you tell me how to slove this matter?Thanks
